Delete timestamp
klips-project/rabbitmq-worker pull request #158
Opened 2023-07-05 06:43 UTC by sdobbert

Deletes old (-49 hours) granule from image mosaic as part of the dataset-rotation worker.

2023-07-06 06:50 UTC, chrismayer requested changes
Thanks for this.

I have a few comments / suggestions to be looked at before merging this.

One general hint: There are a lot of whitespace changes at unrelated code parts, which makes it hard to review the essential changes of this PR.

2023-07-06 06:50 UTC, chrismayer commented on src/dataset-rotation/README.md
> +    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
Comments are not allowed in JSON and being strictly this is no valid JSON. Maybe we better remove the comment. Also it is in German...

2023-07-06 06:50 UTC, chrismayer commented on src/dataset-rotation/index.js
> +        newPath = await grc.imagemosaics.deleteSingleGranule(ws, covStore, coverage, covFileLocation);
`newPath` is not declared as variable, please add `const` or `let`.

2023-07-11 08:13 UTC, chrismayer approved these changes
Code looks good to me, thanks @sdobbert. Untested.

2023-07-11 08:15 UTC, chrismayer commented
Tests are failing, with the message

```
/home/runner/work/rabbitmq-worker/rabbitmq-worker/src/dataset-rotation/index.js
Error:   78:8  error  Unnecessary semicolon  no-extra-semi
```
see https://github.com/klips-project/rabbitmq-worker/actions/runs/5507236560/jobs/10036931263?pr=158

Please make the linter happy before merging ;-)

2023-07-12 12:25 UTC, hblitza approved these changes

2023-07-12 12:26 UTC, sdobbert commented
Thanks for the review.

2023-07-12 12:26 UTC, merged